var conditions = [
  {"code":1000,"text":"Sunny","icon":["sunny","clear"]},
  {"code":1003,"text":"Partly Cloudy","icon":["cloudy","alt-cloudy"]},
  {"code":1006,"text":"Cloudy","icon":["cloudy","alt-cloudy"]},
  {"code":1009,"text":"Overcast","icon":["sunny-overcast","alt-cloudy"]},
  {"code":1030,"text":"Mist","icon":["fog","fog"]},
  {"code":1063,"text":"Patchy rain nearby","icon":["rain","alt-rain"]},
  {"code":1066,"text":"Patchy snow nearby","icon":["snow","alt-snow"]},
  {"code":1069,"text":"Patchy sleet nearby","icon":["snow","alt-snow"]},
  {"code":1072,"text":"Patchy freezing drizzle nearby","icon":["snow","alt-snow"]},
  {"code":1087,"text":"Thundery outbreaks in nearby","icon":["storm-showers","alt-showers"]},
  {"code":1114,"text":"Blowing snow","icon":["snow","alt-snow"]},
  {"code":1117,"text":"Blizzard","icon":["snow","alt-snow"]},
  {"code":1135,"text":"Fog","icon":["fog","fog"]},
  {"code":1147,"text":"Freezing fog","icon":["fog","fog"]},
  {"code":1150,"text":"Patchy light drizzle","icon":["showers","alt-showers"]},
  {"code":1153,"text":"Light drizzle","icon":["showers","alt-showers"]},
  {"code":1168,"text":"Freezing drizzle","icon":["snow","alt-snow"]},
  {"code":1171,"text":"Heavy freezing drizzle","icon":["snow","alt-snow"]},
  {"code":1180,"text":"Patchy light rain","icon":["rain","alt-rain"]},
  {"code":1183,"text":"Light rain","icon":["rain","alt-rain"]},
  {"code":1186,"text":"Moderate rain at times","icon":["rain","alt-rain"]},
  {"code":1189,"text":"Moderate rain","icon":["rain","alt-rain"]},
  {"code":1192,"text":"Heavy rain at times","icon":["rain","alt-rain"]},
  {"code":1195,"text":"Heavy rain","icon":["rain","alt-rain"]},
  {"code":1198,"text":"Light freezing rain","icon":["rain","alt-rain"]},
  {"code":1201,"text":"Moderate or heavy freezing rain","icon":["rain","alt-rain"]},
  {"code":1204,"text":"Light sleet","icon":["snow","alt-snow"]},
  {"code":1207,"text":"Moderate or heavy sleet","icon":["snow","alt-snow"]},
  {"code":1210,"text":"Patchy light snow","icon":["snow","alt-snow"]},
  {"code":1213,"text":"Light snow","icon":["snow","alt-snow"]},
  {"code":1216,"text":"Patchy moderate snow","icon":["snow","alt-snow"]},
  {"code":1219,"text":"Moderate snow","icon":["snow","alt-snow"]},
  {"code":1222,"text":"Patchy heavy snow","icon":["snow","alt-snow"]},
  {"code":1225,"text":"Heavy snow","icon":["snow","alt-snow"]},
  {"code":1237,"text":"Ice pellets","icon":["snow","alt-snow"]},
  {"code":1240,"text":"Light rain shower","icon":["showers","alt-showers"]},
  {"code":1243,"text":"Moderate or heavy rain shower","icon":["showers","alt-showers"]},
  {"code":1246,"text":"Torrential rain shower","icon":["showers","alt-showers"]},
  {"code":1249,"text":"Light sleet showers","icon":["showers","alt-showers"]},
  {"code":1252,"text":"Moderate or heavy sleet showers","icon":["showers","alt-showers"]},
  {"code":1255,"text":"Light snow showers","icon":["showers","alt-showers"]},
  {"code":1258,"text":"Moderate or heavy snow showers","icon":["snow","alt-snow"]},
  {"code":1261,"text":"Light showers of ice pellets","icon":["snow","alt-snow"]},
  {"code":1264,"text":"Moderate or heavy showers of ice pellets","icon":["snow","alt-snow"]},
  {"code":1273,"text":"Patchy light rain in area with thunder","icon":["storm-showers","alt-showers"]},
  {"code":1276,"text":"Moderate or heavy rain in area with thunder","icon":["storm-showers","alt-showers"]},
  {"code":1279,"text":"Patchy light snow in area with thunder","icon":["snow-thunderstorm","alt-snow-thunderstorm"]},
  {"code":1282,"text":"Moderate or heavy snow in area with thunder","icon":["snow-thunderstorm","alt-snow-thunderstorm"]}
];
